name: Checks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: macos-14

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run flake checks
        run: nix flake check --print-build-logs
